# Generated by Django 4.0 on 2024-05-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_article_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentID',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
