# Generated by Django 4.0 on 2024-05-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_department_departmentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentID',
            field=models.CharField(editable=False, max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
